/**
 * Pull the webfonts into the repo so the site can serve them itself.
 *
 * The brief bans a `<link>` to Google Fonts in production: a third-party
 * stylesheet on the critical path is a render-blocking request to a host we do
 * not control, and it is the request that decides when the headline paints.
 * Serving the files from our own origin removes the connection entirely.
 *
 * This script is the provenance record for `public/fonts`. It asks Google for
 * the same CSS a browser would get, keeps the subsets we actually set text in,
 * downloads each woff2, and rewrites the `src` to a local path. Re-run it to
 * add a weight or a script:
 *
 *   node scripts/fetch-fonts.mjs
 *
 * The output is committed. Nothing at build or request time talks to Google.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT_DIR = join(ROOT, "public", "fonts");

/* Google serves woff2 only to browsers that advertise support for it. */
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

/**
 * What to fetch, and which subsets survive.
 *
 * Vietnamese and Greek are dropped: nothing on this site is set in either, and
 * every kept subset is a file a reader may end up downloading.
 */
const FAMILIES = [
  {
    /* Latin pair, loaded on every page in every language. Written into src so
     * it is bundled with the rest of the stylesheet rather than costing a
     * second request on the critical path. */
    file: "../../src/styles.fonts.css",
    families: [
      /* The workhorse. Most of the page is set in this. */
      { query: "Instrument+Sans:ital,wght@0,400..600;1,400..500", slug: "instrument-sans" },
      /* The accent, and only the accent. Roman and italic, no weights above
       * 500: this face is used at display sizes where 400 already has
       * presence, and a bold Garamond is a different, worse typeface. */
      { query: "EB+Garamond:ital,wght@0,400..500;1,400..500", slug: "eb-garamond" },
    ],
    subsets: ["latin", "latin-ext", "cyrillic", "cyrillic-ext"],
  },
  {
    /* Russian pages only. Instrument Sans is Latin-only, so Cyrillic body
     * copy needs a face of its own; Golos Text is a Cyrillic-native
     * neo-grotesk in the same register, which is what keeps a Russian page
     * looking like the same site rather than a translation of it. EB
     * Garamond carries its own Cyrillic, so the serif accent does not
     * change. */
    file: "cyrillic.css",
    families: [{ query: "Golos+Text:wght@400..600", slug: "golos-text" }],
    subsets: ["cyrillic", "cyrillic-ext"],
  },
  {
    /* Arabic pages only, linked by the $lang layout. */
    file: "arabic.css",
    families: [
      { query: "Amiri:wght@400;700", slug: "amiri" },
      { query: "Noto+Sans+Arabic:wght@300..500", slug: "noto-sans-arabic" },
    ],
    subsets: ["arabic"],
  },
  {
    /* Hindi pages only. */
    file: "devanagari.css",
    families: [
      { query: "Noto+Serif+Devanagari:wght@300..500", slug: "noto-serif-devanagari" },
      { query: "Noto+Sans+Devanagari:wght@300..500", slug: "noto-sans-devanagari" },
    ],
    subsets: ["devanagari"],
  },
];

/** Split a Google Fonts stylesheet into `/* subset *\/` + `@font-face` pairs. */
function parseBlocks(css) {
  const blocks = [];
  const re = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g;
  let match;
  while ((match = re.exec(css)) !== null) {
    blocks.push({ subset: match[1], rule: match[2] });
  }
  return blocks;
}

function fieldOf(rule, name) {
  const match = rule.match(new RegExp(`${name}:\\s*([^;]+);`));
  return match ? match[1].trim() : "";
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  const downloaded = new Map();

  for (const bundle of FAMILIES) {
    const out = [
      "/*",
      " * Generated by scripts/fetch-fonts.mjs. Do not edit by hand.",
      " * Source: Google Fonts, served from our own origin.",
      " */",
      "",
    ];

    for (const family of bundle.families) {
      const url = `https://fonts.googleapis.com/css2?family=${family.query}&display=swap`;
      const css = await fetch(url, { headers: { "User-Agent": UA } }).then((r) => {
        if (!r.ok) throw new Error(`${url} responded ${r.status}`);
        return r.text();
      });

      for (const { subset, rule } of parseBlocks(css)) {
        if (!bundle.subsets.includes(subset)) continue;

        const style = fieldOf(rule, "font-style") || "normal";
        const weight = (fieldOf(rule, "font-weight") || "400").replace(/\s+/g, "-");
        const remote = rule.match(/url\((https:[^)]+)\)/)?.[1];
        if (!remote) continue;

        const name = `${family.slug}-${subset}-${weight}-${style}.woff2`;
        if (!downloaded.has(name)) {
          const bytes = await fetch(remote, { headers: { "User-Agent": UA } }).then(async (r) => {
            if (!r.ok) throw new Error(`${remote} responded ${r.status}`);
            return Buffer.from(await r.arrayBuffer());
          });
          await writeFile(join(OUT_DIR, name), bytes);
          downloaded.set(name, bytes.length);
        }

        out.push(
          rule
            .replace(/url\(https:[^)]+\)/, `url(/fonts/${name})`)
            .replace(/\s+/g, " ")
            .replace(/\{ /, "{\n  ")
            .replace(/; /g, ";\n  ")
            .replace(/;\n {2}\}/, ";\n}"),
          "",
        );
      }
    }

    const target = join(OUT_DIR, bundle.file);
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, out.join("\n"));
    console.log(`wrote ${relative(ROOT, target)}`);
  }

  const total = [...downloaded.values()].reduce((a, b) => a + b, 0);
  console.log(`${downloaded.size} files, ${(total / 1024).toFixed(0)} KB total`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
